# Configure regular AutoRecon options at the top of this file.

nmap-append = '-T4 --min-rate=500'
verbose = 3
max-scans = 50

# Configure global options here.
[global]
username-wordlist = '/usr/share/seclists/Usernames/cirt-default-usernames.txt'

# Configure plugin options here.
[dirbuster]
threads = 100
wordlist = [
	'/usr/share/seclists/Discovery/Web-Content/common.txt',
	'/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt',
	'/usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt'
]
ext = 'txt,html,php,asp,aspx,jsp,xml,config,bak'
